name: outpasssecurity
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 
  firebase_core: 
  cloud_firestore: 
  firebase_auth: 
  firebase_messaging: 
  google_fonts: 
  firebase_analytics: 
  flutter_barcode_scanner: 
  intl: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  flutter_launcher_icons: 

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/app_icon.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - images/college_logo.png
    - images/google_logo.png
