name: outpassapp
description: "The CIT Outpass App is a mobile application designed to simplify the outpass request process for students residing in the Chennai Institute of Technology (CIT) college hostels."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_sign_in: ^6.2.1
  google_fonts: ^6.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  intl: ^0.19.0
  connectivity_plus: ^5.0.2
  firebase_messaging: ^14.7.10
  qr_flutter: ^4.1.0
  flutter_native_splash: ^2.3.10
  flutter_windowmanager: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/app_icon.png"
  adaptive_icon_background: "#ffffff"

flutter_native_splash:
  android: true
  ios: true
  image: "images/splash_icon.png"
  color: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - images/splash_icon.png
    - images/google_logo.png
